# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-06 13:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.FloatField()),
                ('to_pay', models.FloatField()),
                ('paid', models.FloatField()),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.FloatField()),
                ('to_pay', models.FloatField()),
                ('paid', models.FloatField()),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.FloatField()),
                ('to_pay', models.FloatField()),
                ('paid', models.FloatField()),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WeddingHall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.FloatField()),
                ('to_pay', models.FloatField()),
                ('paid', models.FloatField()),
                ('done', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WeddingRings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.FloatField()),
                ('to_pay', models.FloatField()),
                ('paid', models.FloatField()),
                ('done', models.BooleanField()),
            ],
        ),
    ]
