# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-06 21:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0003_auto_20170706_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholBeverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.FloatField(null=True)),
                ('to_pay', models.FloatField(null=True)),
                ('paid', models.FloatField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.FloatField(null=True)),
                ('to_pay', models.FloatField(null=True)),
                ('paid', models.FloatField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NonAlcoholBeverages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.FloatField(null=True)),
                ('to_pay', models.FloatField(null=True)),
                ('paid', models.FloatField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cost', models.FloatField(null=True)),
                ('to_pay', models.FloatField(null=True)),
                ('paid', models.FloatField(null=True)),
                ('done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='wedding',
            name='AlcoholBeverages',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.AlcoholBeverages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wedding',
            name='Church',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.Church'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wedding',
            name='NonAlcoholBeverages',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.NonAlcoholBeverages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wedding',
            name='Other',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.Other'),
            preserve_default=False,
        ),
    ]
