# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20170706_2151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wedding',
            name='AlcoholBeverages',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='Band',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='Car',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='Church',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='NonAlcoholBeverages',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='Other',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='Photographer',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='WeddingHall',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='WeddingRings',
        ),
        migrations.AddField(
            model_name='alcoholbeverages',
            name='wedding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.Wedding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='wedding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.Wedding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='wedding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.Wedding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='church',
            name='wedding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.Wedding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonalcoholbeverages',
            name='wedding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.Wedding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='other',
            name='wedding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.Wedding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photographer',
            name='wedding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.Wedding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weddinghall',
            name='wedding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.Wedding'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weddingrings',
            name='wedding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planner.Wedding'),
            preserve_default=False,
        ),
    ]
